# conda env create -f conda-env.yml
name: cloudlabprofile-kubernetes
channels:
  - defaults
dependencies:
  - pip
  - python=3.10
  - pip:
      - ansible-core==2.14.11
      - geni-lib==0.9.9.4
      - netaddr==0.9.0